// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class API_V_TOPMVT
    {
        public string AR_Ref { get; set; }
        public string AR_Design { get; set; }
        public string CT_Num { get; set; }
        public string CT_Intitule { get; set; }
        public short? CT_Type { get; set; }
        public decimal? DL_Qte { get; set; }
        public decimal? DL_MontantHT { get; set; }
        public decimal? DL_MontantTTC { get; set; }
    }
}