// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_ABOENTETE
    {
        public int cbMarq { get; set; }
        public int AB_No { get; set; }
        public string AE_Ref { get; set; }
        public int? CO_No { get; set; }
        public short? AE_Period { get; set; }
        public short? AE_Devise { get; set; }
        public decimal? AE_Cours { get; set; }
        public int DE_No { get; set; }
        public int? LI_No { get; set; }
        public string CT_NumPayeur { get; set; }
        public short? AE_Expedit { get; set; }
        public short? AE_NbFacture { get; set; }
        public short? AE_BLFact { get; set; }
        public decimal? AE_TxEscompte { get; set; }
        public string CA_Num { get; set; }
        public string AE_Coord01 { get; set; }
        public string AE_Coord02 { get; set; }
        public string AE_Coord03 { get; set; }
        public string AE_Coord04 { get; set; }
        public short? AE_Condition { get; set; }
        public short? AE_Tarif { get; set; }
        public short? AE_Colisage { get; set; }
        public short? AE_TypeColis { get; set; }
        public short? AE_Transaction { get; set; }
        public short? AE_Langue { get; set; }
        public short? AE_Regime { get; set; }
        public short? N_CatCompta { get; set; }
        public short? AE_BaseCalcul { get; set; }
        public short? AE_Genere { get; set; }
        public string CG_Num { get; set; }
        public string CA_NumIFRS { get; set; }
        public string CT_NumCentrale { get; set; }
        public string AE_Contact { get; set; }
    }
}