// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_ARTSTOCK
    {
        public int cbMarq { get; set; }
        public string AR_Ref { get; set; }
        public int DE_No { get; set; }
        public decimal? AS_QteMini { get; set; }
        public decimal? AS_QteMaxi { get; set; }
        public decimal? AS_MontSto { get; set; }
        public decimal? AS_QteSto { get; set; }
        public decimal? AS_QteRes { get; set; }
        public decimal? AS_QteCom { get; set; }
        public short? AS_Principal { get; set; }
        public decimal? AS_QteResCM { get; set; }
        public decimal? AS_QteComCM { get; set; }
        public decimal? AS_QtePrepa { get; set; }
        public int? DP_NoPrincipal { get; set; }
        public int? DP_NoControle { get; set; }
        public decimal? AS_QteAControler { get; set; }
    }
}