// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_ARTSTOCKEMPL
    {
        public int cbMarq { get; set; }
        public string AR_Ref { get; set; }
        public int DE_No { get; set; }
        public int DP_No { get; set; }
        public decimal? AE_QteSto { get; set; }
        public decimal? AE_QtePrepa { get; set; }
        public decimal? AE_QteAControler { get; set; }
    }
}