// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_ARTICLE
    {
        public int cbMarq { get; set; }
        public string AR_Ref { get; set; }
        public string AR_Design { get; set; }
        public string FA_CodeFamille { get; set; }
        public string AR_Substitut { get; set; }
        public string AR_Raccourci { get; set; }
        public short? AR_Garantie { get; set; }
        public short? AR_UnitePoids { get; set; }
        public decimal? AR_PoidsNet { get; set; }
        public decimal? AR_PoidsBrut { get; set; }
        public short? AR_UniteVen { get; set; }
        public decimal? AR_PrixAch { get; set; }
        public decimal? AR_Coef { get; set; }
        public decimal? AR_PrixVen { get; set; }
        public short? AR_PrixTTC { get; set; }
        public short? AR_Gamme1 { get; set; }
        public short? AR_Gamme2 { get; set; }
        public short? AR_SuiviStock { get; set; }
        public short? AR_Nomencl { get; set; }
        public string AR_Stat01 { get; set; }
        public string AR_Stat02 { get; set; }
        public string AR_Stat03 { get; set; }
        public string AR_Stat04 { get; set; }
        public string AR_Stat05 { get; set; }
        public short? AR_Escompte { get; set; }
        public short? AR_Delai { get; set; }
        public short? AR_HorsStat { get; set; }
        public short? AR_VteDebit { get; set; }
        public short? AR_NotImp { get; set; }
        public short? AR_Sommeil { get; set; }
        public string AR_Langue1 { get; set; }
        public string AR_Langue2 { get; set; }
        public string AR_EdiCode { get; set; }
        public string AR_CodeBarre { get; set; }
        public string AR_CodeFiscal { get; set; }
        public string AR_Pays { get; set; }
        public string AR_Frais01FR_Denomination { get; set; }
        public decimal? AR_Frais01FR_Rem01REM_Valeur { get; set; }
        public short? AR_Frais01FR_Rem01REM_Type { get; set; }
        public decimal? AR_Frais01FR_Rem02REM_Valeur { get; set; }
        public short? AR_Frais01FR_Rem02REM_Type { get; set; }
        public decimal? AR_Frais01FR_Rem03REM_Valeur { get; set; }
        public short? AR_Frais01FR_Rem03REM_Type { get; set; }
        public string AR_Frais02FR_Denomination { get; set; }
        public decimal? AR_Frais02FR_Rem01REM_Valeur { get; set; }
        public short? AR_Frais02FR_Rem01REM_Type { get; set; }
        public decimal? AR_Frais02FR_Rem02REM_Valeur { get; set; }
        public short? AR_Frais02FR_Rem02REM_Type { get; set; }
        public decimal? AR_Frais02FR_Rem03REM_Valeur { get; set; }
        public short? AR_Frais02FR_Rem03REM_Type { get; set; }
        public string AR_Frais03FR_Denomination { get; set; }
        public decimal? AR_Frais03FR_Rem01REM_Valeur { get; set; }
        public short? AR_Frais03FR_Rem01REM_Type { get; set; }
        public decimal? AR_Frais03FR_Rem02REM_Valeur { get; set; }
        public short? AR_Frais03FR_Rem02REM_Type { get; set; }
        public decimal? AR_Frais03FR_Rem03REM_Valeur { get; set; }
        public short? AR_Frais03FR_Rem03REM_Type { get; set; }
        public short? AR_Condition { get; set; }
        public decimal? AR_PUNet { get; set; }
        public short? AR_Contremarque { get; set; }
        public short? AR_FactPoids { get; set; }
        public short? AR_FactForfait { get; set; }
        public short? AR_SaisieVar { get; set; }
        public short? AR_Transfere { get; set; }
        public short? AR_Publie { get; set; }
        public string AR_Photo { get; set; }
        public decimal? AR_PrixAchNouv { get; set; }
        public decimal? AR_CoefNouv { get; set; }
        public decimal? AR_PrixVenNouv { get; set; }
        public decimal? AR_CoutStd { get; set; }
        public decimal? AR_QteComp { get; set; }
        public decimal? AR_QteOperatoire { get; set; }
        public int? CO_No { get; set; }
        public short? AR_Prevision { get; set; }
        public int? CL_No1 { get; set; }
        public int? CL_No2 { get; set; }
        public int? CL_No3 { get; set; }
        public int? CL_No4 { get; set; }
        public short? AR_Type { get; set; }
        public string RP_CodeDefaut { get; set; }
        public short? AR_Nature { get; set; }
        public short? AR_DelaiFabrication { get; set; }
        public short? AR_NbColis { get; set; }
        public short? AR_DelaiPeremption { get; set; }
        public short? AR_DelaiSecurite { get; set; }
        public short? AR_Fictif { get; set; }
        public short? AR_SousTraitance { get; set; }
        public short? AR_TypeLancement { get; set; }
        public short? AR_Cycle { get; set; }
        public short? AR_Criticite { get; set; }
    }
}