// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_ARTENUMREF
    {
        public int cbMarq { get; set; }
        public string AR_Ref { get; set; }
        public int? AG_No1 { get; set; }
        public int? AG_No2 { get; set; }
        public string AE_Ref { get; set; }
        public decimal? AE_PrixAch { get; set; }
        public string AE_CodeBarre { get; set; }
        public decimal? AE_PrixAchNouv { get; set; }
        public string AE_EdiCode { get; set; }
        public short? AE_Sommeil { get; set; }
    }
}