// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_ARTPRIX
    {
        public int cbMarq { get; set; }
        public string AR_Ref { get; set; }
        public int? AG_No1 { get; set; }
        public int? AG_No2 { get; set; }
        public decimal? AR_PUNet { get; set; }
        public decimal? AR_CoutStd { get; set; }
    }
}