// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_ARTFOURNISS
    {
        public int cbMarq { get; set; }
        public string AR_Ref { get; set; }
        public string CT_Num { get; set; }
        public string AF_RefFourniss { get; set; }
        public decimal? AF_PrixAch { get; set; }
        public short? AF_Unite { get; set; }
        public decimal? AF_Conversion { get; set; }
        public short? AF_DelaiAppro { get; set; }
        public short? AF_Garantie { get; set; }
        public decimal? AF_Colisage { get; set; }
        public decimal? AF_QteMini { get; set; }
        public short? AF_QteMont { get; set; }
        public short? EG_Champ { get; set; }
        public short? AF_Principal { get; set; }
        public decimal? AF_PrixDev { get; set; }
        public short? AF_Devise { get; set; }
        public decimal? AF_Remise { get; set; }
        public decimal? AF_ConvDiv { get; set; }
        public short? AF_TypeRem { get; set; }
        public string AF_CodeBarre { get; set; }
        public decimal? AF_PrixAchNouv { get; set; }
        public decimal? AF_PrixDevNouv { get; set; }
        public decimal? AF_RemiseNouv { get; set; }
    }
}