// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_ARTCOMPTA
    {
        public int cbMarq { get; set; }
        public string AR_Ref { get; set; }
        public short? ACP_Type { get; set; }
        public short? ACP_Champ { get; set; }
        public string ACP_ComptaCPT_CompteG { get; set; }
        public string ACP_ComptaCPT_CompteA { get; set; }
        public string ACP_ComptaCPT_Taxe1 { get; set; }
        public string ACP_ComptaCPT_Taxe2 { get; set; }
        public string ACP_ComptaCPT_Taxe3 { get; set; }
        public string ACP_ComptaCPT_TaxeAnc1 { get; set; }
        public string ACP_ComptaCPT_TaxeAnc2 { get; set; }
        public string ACP_ComptaCPT_TaxeAnc3 { get; set; }
        public short? ACP_TypeFacture { get; set; }
    }
}