// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_ARTGAMME
    {
        public int cbMarq { get; set; }
        public string AR_Ref { get; set; }
        public int? AG_No { get; set; }
        public string EG_Enumere { get; set; }
        public short? AG_Type { get; set; }
    }
}