// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_BANQUET
    {
        public int cbMarq { get; set; }
        public string CT_Num { get; set; }
        public short BT_Num { get; set; }
        public string BT_Intitule { get; set; }
        public string BT_Banque { get; set; }
        public string BT_Guichet { get; set; }
        public string BT_Compte { get; set; }
        public string BT_Cle { get; set; }
        public string BT_Commentaire { get; set; }
        public short? BT_Struct { get; set; }
        public short? N_Devise { get; set; }
        public string BT_Adresse { get; set; }
        public string BT_Complement { get; set; }
        public string BT_CodePostal { get; set; }
        public string BT_Ville { get; set; }
        public string BT_Pays { get; set; }
        public string BT_BIC { get; set; }
        public string BT_IBAN { get; set; }
        public short? BT_CalculIBAN { get; set; }
        public string BT_NomAgence { get; set; }
        public string BT_CodeRegion { get; set; }
        public string BT_PaysAgence { get; set; }
        public int? MD_No { get; set; }
    }
}