// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_CATALOGUE
    {
        public int cbMarq { get; set; }
        public int? CL_No { get; set; }
        public string CL_Intitule { get; set; }
        public string CL_Code { get; set; }
        public short? CL_Stock { get; set; }
        public int? CL_NoParent { get; set; }
        public short? CL_Niveau { get; set; }
    }
}