// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_CAISSE
    {
        public int cbMarq { get; set; }
        public int? CA_No { get; set; }
        public string CA_Intitule { get; set; }
        public int DE_No { get; set; }
        public int? CO_No { get; set; }
        public int? CO_NoCaissier { get; set; }
        public string CT_Num { get; set; }
        public string JO_Num { get; set; }
        public short? CA_IdentifCaissier { get; set; }
        public short? N_Comptoir { get; set; }
        public short? N_Clavier { get; set; }
        public short? CA_LignesAfficheur { get; set; }
        public short? CA_ColonnesAfficheur { get; set; }
        public short? CA_ImpTicket { get; set; }
        public short? CA_SaisieVendeur { get; set; }
        public short? CA_Souche { get; set; }
    }
}