// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_COMPTEG
    {
        public int cbMarq { get; set; }
        public string CG_Num { get; set; }
        public short? CG_Type { get; set; }
        public string CG_Intitule { get; set; }
        public string CG_Classement { get; set; }
        public short? N_Nature { get; set; }
        public short? CG_Report { get; set; }
        public string CR_Num { get; set; }
        public string CG_Raccourci { get; set; }
        public short? CG_Saut { get; set; }
        public short? CG_Regroup { get; set; }
        public short? CG_Analytique { get; set; }
        public short? CG_Echeance { get; set; }
        public short? CG_Quantite { get; set; }
        public short? CG_Lettrage { get; set; }
        public short? CG_Tiers { get; set; }
        public short? CG_Devise { get; set; }
        public short? N_Devise { get; set; }
        public string TA_Code { get; set; }
        public short? CG_Sommeil { get; set; }
        public short? CG_ReportAnal { get; set; }
    }
}