// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_CONTACTT
    {
        public int cbMarq { get; set; }
        public string CT_Num { get; set; }
        public string CT_Nom { get; set; }
        public string CT_Prenom { get; set; }
        public short? N_Service { get; set; }
        public string CT_Fonction { get; set; }
        public string CT_Telephone { get; set; }
        public string CT_TelPortable { get; set; }
        public string CT_Telecopie { get; set; }
        public string CT_EMail { get; set; }
        public short? CT_Civilite { get; set; }
        public short? N_Contact { get; set; }
        public int? CT_No { get; set; }
    }
}