// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_COMPTEGA
    {
        public int cbMarq { get; set; }
        public string CG_Num { get; set; }
        public short N_Analytique { get; set; }
        public string CA_Num { get; set; }
        public short? CG_ATRepart { get; set; }
        public decimal? CG_AVRepart { get; set; }
    }
}