// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_COLLABORATEUR
    {
        public int cbMarq { get; set; }
        public int? CO_No { get; set; }
        public string CO_Nom { get; set; }
        public string CO_Prenom { get; set; }
        public string CO_Fonction { get; set; }
        public string CO_Adresse { get; set; }
        public string CO_Complement { get; set; }
        public string CO_CodePostal { get; set; }
        public string CO_Ville { get; set; }
        public string CO_CodeRegion { get; set; }
        public string CO_Pays { get; set; }
        public string CO_Service { get; set; }
        public short? CO_Vendeur { get; set; }
        public short? CO_Caissier { get; set; }
        public short? CO_Acheteur { get; set; }
        public string CO_Telephone { get; set; }
        public string CO_Telecopie { get; set; }
        public string CO_EMail { get; set; }
        public short? CO_Receptionnaire { get; set; }
        public int? PROT_No { get; set; }
        public string CO_TelPortable { get; set; }
        public short? CO_ChargeRecouvr { get; set; }
        public string CO_Matricule { get; set; }
        public short? CO_Financier { get; set; }
        public short? CO_Transmission { get; set; }
    }
}