// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_COMPTER
    {
        public int cbMarq { get; set; }
        public string CR_Num { get; set; }
        public short? CR_Type { get; set; }
        public string CR_Intitule { get; set; }
        public string CR_Classement { get; set; }
        public short? CR_Saut { get; set; }
    }
}