// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_CREGLEMENT
    {
        public int cbMarq { get; set; }
        public int? RG_No { get; set; }
        public string CT_NumPayeur { get; set; }
        public DateTime? RG_Date { get; set; }
        public string RG_Reference { get; set; }
        public string RG_Libelle { get; set; }
        public decimal? RG_Montant { get; set; }
        public decimal? RG_MontantDev { get; set; }
        public short? N_Reglement { get; set; }
        public short? RG_Impute { get; set; }
        public short? RG_Compta { get; set; }
        public int? EC_No { get; set; }
        public short? RG_Type { get; set; }
        public decimal? RG_Cours { get; set; }
        public short? N_Devise { get; set; }
        public string JO_Num { get; set; }
        public string CG_NumCont { get; set; }
        public DateTime? RG_Impaye { get; set; }
        public string CG_Num { get; set; }
        public short? RG_TypeReg { get; set; }
        public string RG_Heure { get; set; }
        public string RG_Piece { get; set; }
        public int? CA_No { get; set; }
        public int? CO_NoCaissier { get; set; }
        public short? RG_Banque { get; set; }
        public short? RG_Transfere { get; set; }
        public short RG_Cloture { get; set; }
        public short? RG_Ticket { get; set; }
        public short? RG_Souche { get; set; }
        public string CT_NumPayeurOrig { get; set; }
        public DateTime? RG_DateEchCont { get; set; }
        public string CG_NumEcart { get; set; }
        public string JO_NumEcart { get; set; }
        public decimal? RG_MontantEcart { get; set; }
        public int? RG_NoBonAchat { get; set; }
    }
}