// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_DEPOTEMPL
    {
        public int cbMarq { get; set; }
        public int DE_No { get; set; }
        public int? DP_No { get; set; }
        public string DP_Code { get; set; }
        public string DP_Intitule { get; set; }
        public short? DP_Zone { get; set; }
        public short? DP_Type { get; set; }
    }
}