// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_DEPOT
    {
        public int cbMarq { get; set; }
        public int? DE_No { get; set; }
        public string DE_Intitule { get; set; }
        public string DE_Adresse { get; set; }
        public string DE_Complement { get; set; }
        public string DE_CodePostal { get; set; }
        public string DE_Ville { get; set; }
        public string DE_Contact { get; set; }
        public short? DE_Principal { get; set; }
        public short? DE_CatCompta { get; set; }
        public string DE_Region { get; set; }
        public string DE_Pays { get; set; }
        public string DE_EMail { get; set; }
        public string DE_Code { get; set; }
        public string DE_Telephone { get; set; }
        public string DE_Telecopie { get; set; }
        public int? DE_Replication { get; set; }
        public int? DP_NoDefaut { get; set; }
        public short? DE_Exclure { get; set; }
    }
}