// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_DEPOTUSER
    {
        public int cbMarq { get; set; }
        public int? DE_No { get; set; }
        public int? PROT_No { get; set; }
    }
}