// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_DEPOTCONTACT
    {
        public int cbMarq { get; set; }
        public int DE_No { get; set; }
        public string DC_Nom { get; set; }
        public string DC_Prenom { get; set; }
        public short? N_Service { get; set; }
        public string DC_Fonction { get; set; }
        public string DC_Telephone { get; set; }
        public string DC_TelPortable { get; set; }
        public string DC_Telecopie { get; set; }
        public string DC_EMail { get; set; }
        public short? DC_Civilite { get; set; }
        public short? N_Contact { get; set; }
        public int? DC_No { get; set; }
    }
}