// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_DOCCURRENTPIECE
    {
        public int cbMarq { get; set; }
        public short? DC_Domaine { get; set; }
        public short? DC_IdCol { get; set; }
        public short? DC_Souche { get; set; }
        public string DC_Piece { get; set; }
    }
}