// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_DOCLIGNEEMPL
    {
        public int cbMarq { get; set; }
        public int DL_No { get; set; }
        public int DP_No { get; set; }
        public decimal? DL_Qte { get; set; }
        public decimal? DL_QteAControler { get; set; }
    }
}