// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_DOCREGL
    {
        public int cbMarq { get; set; }
        public int? DR_No { get; set; }
        public short? DO_Domaine { get; set; }
        public short? DO_Type { get; set; }
        public string DO_Piece { get; set; }
        public short? DR_TypeRegl { get; set; }
        public DateTime? DR_Date { get; set; }
        public string DR_Libelle { get; set; }
        public decimal? DR_Pourcent { get; set; }
        public decimal? DR_Montant { get; set; }
        public decimal? DR_MontantDev { get; set; }
        public short? DR_Equil { get; set; }
        public int? EC_No { get; set; }
        public short? DR_Regle { get; set; }
        public short? N_Reglement { get; set; }
    }
}