// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_EBANQUE
    {
        public int cbMarq { get; set; }
        public int BQ_No { get; set; }
        public string EB_Banque { get; set; }
        public string EB_Guichet { get; set; }
        public string EB_Compte { get; set; }
        public string EB_Cle { get; set; }
        public string EB_Commentaire { get; set; }
        public string JO_Num { get; set; }
        public short? EB_Struct { get; set; }
        public short? N_Devise { get; set; }
        public int? EB_No { get; set; }
        public string EB_Abrege { get; set; }
        public string EB_Emetteur01 { get; set; }
        public string EB_Emetteur02 { get; set; }
        public string EB_Emetteur03 { get; set; }
        public string EB_Adresse { get; set; }
        public string EB_Complement { get; set; }
        public string EB_CodePostal { get; set; }
        public string EB_Ville { get; set; }
        public string EB_Pays { get; set; }
        public string EB_BIC { get; set; }
        public string EB_IBAN { get; set; }
        public short? EB_CalculIBAN { get; set; }
        public string EB_NomAgence { get; set; }
        public string JO_NumEscompte { get; set; }
        public string JO_NumEncaiss { get; set; }
        public short? EB_IntraGroupe { get; set; }
        public string EB_RaisonSocBenef { get; set; }
        public string EB_AdresseBenef { get; set; }
        public string EB_ComplementBenef { get; set; }
        public string EB_CodePostalBenef { get; set; }
        public string EB_VilleBenef { get; set; }
        public string EB_PaysBenef { get; set; }
        public string EB_SiretBenef { get; set; }
        public string EB_CodeRegionBenef { get; set; }
        public string EB_CodeRegion { get; set; }
        public string EB_PaysAgence { get; set; }
        public string EB_FileExtrait { get; set; }
        public short? EB_TresoPublic { get; set; }
        public short? EB_BanqueDeFrance { get; set; }
        public string EB_TPServiceDepot { get; set; }
        public short? EB_TPTypeService { get; set; }
        public string EB_TPCodique { get; set; }
        public string EB_TPIBAN { get; set; }
        public string EB_TPBIC { get; set; }
        public short? EB_TPRemise51 { get; set; }
        public string EB_TPIdentifiant51 { get; set; }
        public string EB_BDFCodeRemettant { get; set; }
    }
}