// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_ECRITUREA
    {
        public int cbMarq { get; set; }
        public int EC_No { get; set; }
        public short N_Analytique { get; set; }
        public short? EA_Ligne { get; set; }
        public string CA_Num { get; set; }
        public decimal? EA_Montant { get; set; }
        public decimal? EA_Quantite { get; set; }
    }
}