// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_ECRITUREF
    {
        public int cbMarq { get; set; }
        public int? EF_No { get; set; }
        public DateTime? EF_Date { get; set; }
        public string EF_Piece { get; set; }
        public string CG_Num { get; set; }
        public string EF_Intitule { get; set; }
        public short? EF_Sens { get; set; }
        public decimal? EF_Montant { get; set; }
        public short? EF_Type { get; set; }
    }
}