// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_ENUMCOND
    {
        public int cbMarq { get; set; }
        public short? EC_Champ { get; set; }
        public string EC_Enumere { get; set; }
        public decimal? EC_Quantite { get; set; }
        public string EC_EdiCode { get; set; }
    }
}