// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_ENUMGAMME
    {
        public int cbMarq { get; set; }
        public short? EG_Champ { get; set; }
        public short? EG_Ligne { get; set; }
        public string EG_Enumere { get; set; }
        public decimal? EG_BorneSup { get; set; }
    }
}