// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_FAMCLIENT
    {
        public int cbMarq { get; set; }
        public string FA_CodeFamille { get; set; }
        public string CT_Num { get; set; }
        public decimal? FC_Remise { get; set; }
    }
}