// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_FAMCOMPTA
    {
        public int cbMarq { get; set; }
        public string FA_CodeFamille { get; set; }
        public short? FCP_Type { get; set; }
        public short? FCP_Champ { get; set; }
        public string FCP_ComptaCPT_CompteG { get; set; }
        public string FCP_ComptaCPT_CompteA { get; set; }
        public string FCP_ComptaCPT_Taxe1 { get; set; }
        public string FCP_ComptaCPT_Taxe2 { get; set; }
        public string FCP_ComptaCPT_Taxe3 { get; set; }
        public DateTime? FCP_ComptaCPT_Date1 { get; set; }
        public DateTime? FCP_ComptaCPT_Date2 { get; set; }
        public DateTime? FCP_ComptaCPT_Date3 { get; set; }
        public string FCP_ComptaCPT_TaxeAnc1 { get; set; }
        public string FCP_ComptaCPT_TaxeAnc2 { get; set; }
        public string FCP_ComptaCPT_TaxeAnc3 { get; set; }
        public short? FCP_TypeFacture { get; set; }
    }
}