// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_GAMSTOCK
    {
        public int cbMarq { get; set; }
        public string AR_Ref { get; set; }
        public int? AG_No1 { get; set; }
        public int? AG_No2 { get; set; }
        public int DE_No { get; set; }
        public decimal? GS_MontSto { get; set; }
        public decimal? GS_QteSto { get; set; }
        public decimal? GS_QteRes { get; set; }
        public decimal? GS_QteCom { get; set; }
        public decimal? GS_QteResCM { get; set; }
        public decimal? GS_QteComCM { get; set; }
        public decimal? GS_QteMini { get; set; }
        public decimal? GS_QteMaxi { get; set; }
        public decimal? GS_QtePrepa { get; set; }
        public int? DP_NoPrincipal { get; set; }
        public int? DP_NoControle { get; set; }
        public decimal? GS_QteAControler { get; set; }
    }
}