// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_GAMSTOCKEMPL
    {
        public int cbMarq { get; set; }
        public string AR_Ref { get; set; }
        public int? AG_No1 { get; set; }
        public int? AG_No2 { get; set; }
        public int DE_No { get; set; }
        public int DP_No { get; set; }
        public decimal? GE_QteSto { get; set; }
        public decimal? GE_QtePrepa { get; set; }
        public decimal? GE_QteAControler { get; set; }
    }
}