// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_JMOUV
    {
        public int cbMarq { get; set; }
        public string JO_Num { get; set; }
        public DateTime JM_Date { get; set; }
        public short? JM_Cloture { get; set; }
        public short? JM_Impression { get; set; }
    }
}