// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_JOURNAUXA
    {
        public int cbMarq { get; set; }
        public string JA_Num { get; set; }
        public string JA_Intitule { get; set; }
        public short? JA_Sommeil { get; set; }
        public short? JA_IFRS { get; set; }
    }
}