// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_JOURNAUX
    {
        public int cbMarq { get; set; }
        public string JO_Num { get; set; }
        public string JO_Intitule { get; set; }
        public string CG_Num { get; set; }
        public short? JO_Type { get; set; }
        public short? JO_NumPiece { get; set; }
        public short? JO_Contrepartie { get; set; }
        public short? JO_SaisAnal { get; set; }
        public short? JO_NotCalcTot { get; set; }
        public short? JO_Rappro { get; set; }
        public short? JO_Sommeil { get; set; }
        public short? JO_IFRS { get; set; }
        public short? JO_Reglement { get; set; }
        public short? JO_SuiviTreso { get; set; }
    }
}