// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_LIVRAISON
    {
        public int cbMarq { get; set; }
        public int LI_No { get; set; }
        public string CT_Num { get; set; }
        public string LI_Intitule { get; set; }
        public string LI_Adresse { get; set; }
        public string LI_Complement { get; set; }
        public string LI_CodePostal { get; set; }
        public string LI_Ville { get; set; }
        public string LI_CodeRegion { get; set; }
        public string LI_Pays { get; set; }
        public string LI_Contact { get; set; }
        public short? N_Expedition { get; set; }
        public short? N_Condition { get; set; }
        public short? LI_Principal { get; set; }
        public string LI_Telephone { get; set; }
        public string LI_Telecopie { get; set; }
        public string LI_EMail { get; set; }
    }
}