// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_NOMENCLAT
    {
        public int cbMarq { get; set; }
        public string AR_Ref { get; set; }
        public string NO_RefDet { get; set; }
        public decimal? NO_Qte { get; set; }
        public int? AG_No1 { get; set; }
        public int? AG_No2 { get; set; }
        public short? NO_Type { get; set; }
        public decimal? NO_Repartition { get; set; }
        public string NO_Operation { get; set; }
        public string NO_Commentaire { get; set; }
        public int? DE_No { get; set; }
        public short? NO_Ordre { get; set; }
        public int? AG_No1Comp { get; set; }
        public int? AG_No2Comp { get; set; }
        public short? NO_SousTraitance { get; set; }
    }
}