// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_PAYS
    {
        public int cbMarq { get; set; }
        public string PA_Intitule { get; set; }
        public string PA_Code { get; set; }
        public string PA_CodeEdi { get; set; }
        public decimal? PA_Assurance { get; set; }
        public decimal? PA_Transport { get; set; }
        public string PA_CodeISO2 { get; set; }
        public short? PA_SEPA { get; set; }
        public int? PA_No { get; set; }
    }
}