// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_PIECEG
    {
        public int cbMarq { get; set; }
        public int PI_No { get; set; }
        public short PG_Ligne { get; set; }
        public string PG_Jour { get; set; }
        public string PG_Piece { get; set; }
        public string PG_RefPiece { get; set; }
        public string CG_Num { get; set; }
        public string CG_NumCont { get; set; }
        public string CT_Num { get; set; }
        public string PG_Intitule { get; set; }
        public short? N_Reglement { get; set; }
        public string PG_Echeance { get; set; }
        public string PG_Parite { get; set; }
        public string PG_Quantite { get; set; }
        public short? N_Devise { get; set; }
        public short? PG_Sens { get; set; }
        public string PG_Montant { get; set; }
        public string CT_NumCont { get; set; }
        public string PG_Devise { get; set; }
        public string PG_InfoL01 { get; set; }
        public string PG_InfoL02 { get; set; }
        public string PG_InfoL03 { get; set; }
        public string PG_InfoL04 { get; set; }
        public string PG_InfoL05 { get; set; }
        public string PG_InfoL06 { get; set; }
        public string PG_InfoL07 { get; set; }
        public string PG_InfoL08 { get; set; }
        public string PG_InfoL09 { get; set; }
        public string PG_InfoL10 { get; set; }
        public string PG_InfoL11 { get; set; }
        public string PG_InfoL12 { get; set; }
        public string PG_InfoL13 { get; set; }
        public string PG_InfoL14 { get; set; }
        public string PG_InfoL15 { get; set; }
        public string PG_InfoL16 { get; set; }
        public string PG_InfoL17 { get; set; }
        public string PG_InfoL18 { get; set; }
        public string PG_InfoL19 { get; set; }
        public string PG_InfoL20 { get; set; }
        public string PG_InfoL21 { get; set; }
        public string PG_InfoL22 { get; set; }
        public string PG_InfoL23 { get; set; }
        public string PG_InfoL24 { get; set; }
        public string PG_InfoL25 { get; set; }
        public string PG_InfoL26 { get; set; }
        public string PG_InfoL27 { get; set; }
        public string PG_InfoL28 { get; set; }
        public string PG_InfoL29 { get; set; }
        public string PG_InfoL30 { get; set; }
        public string PG_InfoL31 { get; set; }
        public string PG_InfoL32 { get; set; }
        public string PG_InfoL33 { get; set; }
        public string PG_InfoL34 { get; set; }
        public string PG_InfoL35 { get; set; }
        public string PG_InfoL36 { get; set; }
        public string PG_InfoL37 { get; set; }
        public string PG_InfoL38 { get; set; }
        public string PG_InfoL39 { get; set; }
        public string PG_InfoL40 { get; set; }
        public string PG_InfoL41 { get; set; }
        public string PG_InfoL42 { get; set; }
        public string PG_InfoL43 { get; set; }
        public string PG_InfoL44 { get; set; }
        public string PG_InfoL45 { get; set; }
        public string PG_InfoL46 { get; set; }
        public string PG_InfoL47 { get; set; }
        public string PG_InfoL48 { get; set; }
        public string PG_InfoL49 { get; set; }
        public string PG_InfoL50 { get; set; }
        public string PG_InfoL51 { get; set; }
        public string PG_InfoL52 { get; set; }
        public string PG_InfoL53 { get; set; }
        public string PG_InfoL54 { get; set; }
        public string PG_InfoL55 { get; set; }
        public string PG_InfoL56 { get; set; }
        public string PG_InfoL57 { get; set; }
        public string PG_InfoL58 { get; set; }
        public string PG_InfoL59 { get; set; }
        public string PG_InfoL60 { get; set; }
        public string PG_InfoL61 { get; set; }
        public string PG_InfoL62 { get; set; }
        public string PG_InfoL63 { get; set; }
        public string PG_InfoL64 { get; set; }
        public string TA_Code { get; set; }
        public short? TA_Provenance { get; set; }
        public string PG_Reference { get; set; }
    }
}