// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_PIECE
    {
        public int cbMarq { get; set; }
        public int PI_No { get; set; }
        public string PI_Intitule { get; set; }
        public string PI_Raccourci { get; set; }
        public short? JO_Type { get; set; }
        public string JO_Num { get; set; }
    }
}