// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_PIECEA
    {
        public int cbMarq { get; set; }
        public int PI_No { get; set; }
        public short PG_Ligne { get; set; }
        public short? PA_Ligne { get; set; }
        public short? N_Analytique { get; set; }
        public string CA_Num { get; set; }
        public short? PA_TMontant { get; set; }
        public decimal? PA_VMontant { get; set; }
        public short? PA_TQuantite { get; set; }
        public decimal? PA_VQuantite { get; set; }
    }
}