// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_PROTECTIONCPTA
    {
        public int cbMarq { get; set; }
        public string PROT_User { get; set; }
        public string PROT_Description { get; set; }
        public short? PROT_Right { get; set; }
        public int? PROT_No { get; set; }
        public string PROT_EMail { get; set; }
        public int? PROT_UserProfil { get; set; }
        public short? PROT_Administrator { get; set; }
        public DateTime? PROT_DatePwd { get; set; }
        public DateTime? PROT_LastLoginDate { get; set; }
        public string PROT_LastLoginTime { get; set; }
        public short? PROT_PwdStatus { get; set; }
        public short? PROT_Disabled { get; set; }
        public int? PROT_ApplicationRight { get; set; }
    }
}