// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_REGLECH
    {
        public int cbMarq { get; set; }
        public int RG_No { get; set; }
        public int DR_No { get; set; }
        public short? DO_Domaine { get; set; }
        public short? DO_Type { get; set; }
        public string DO_Piece { get; set; }
        public decimal? RC_Montant { get; set; }
        public short? RG_TypeReg { get; set; }
    }
}