// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_REGLEARCHIVE
    {
        public int cbMarq { get; set; }
        public string TA_Piece { get; set; }
        public decimal? RA_Montant { get; set; }
        public short? N_Devise { get; set; }
        public decimal? RA_MontantDev { get; set; }
        public short? N_Reglement { get; set; }
        public DateTime? RA_Date { get; set; }
        public int? CA_No { get; set; }
    }
}