// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_TARIF
    {
        public int cbMarq { get; set; }
        public int? TF_No { get; set; }
        public string TF_Intitule { get; set; }
        public short? TF_Interes { get; set; }
        public DateTime? TF_Debut { get; set; }
        public DateTime? TF_Fin { get; set; }
        public short? TF_Objectif { get; set; }
        public short? TF_Domaine { get; set; }
        public short? TF_Base { get; set; }
        public short? TF_Calcul { get; set; }
        public string AR_Ref { get; set; }
        public decimal? TF_Remise01REM_Valeur { get; set; }
        public short? TF_Remise01REM_Type { get; set; }
        public decimal? TF_Remise02REM_Valeur { get; set; }
        public short? TF_Remise02REM_Type { get; set; }
        public decimal? TF_Remise03REM_Valeur { get; set; }
        public short? TF_Remise03REM_Type { get; set; }
        public short? TF_Type { get; set; }
        public string CT_Num { get; set; }
    }
}