// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class F_TAXE
    {
        public int cbMarq { get; set; }
        public string TA_Intitule { get; set; }
        public short? TA_TTaux { get; set; }
        public decimal? TA_Taux { get; set; }
        public short? TA_Type { get; set; }
        public string CG_Num { get; set; }
        public int TA_No { get; set; }
        public string TA_Code { get; set; }
        public short? TA_NP { get; set; }
        public short? TA_Sens { get; set; }
        public short? TA_Provenance { get; set; }
        public string TA_Regroup { get; set; }
        public decimal? TA_Assujet { get; set; }
        public string TA_GrilleBase { get; set; }
        public string TA_GrilleTaxe { get; set; }
        public string TA_EdiCode { get; set; }
    }
}