// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class P_DOSSIERCIAL
    {
        public int cbMarq { get; set; }
        public string D_RaisonS { get; set; }
        public string D_FormatQte { get; set; }
        public string D_FormatPrix { get; set; }
        public short? N_DeviseCompte { get; set; }
        public short? N_DeviseEquival { get; set; }
        public DateTime? D_ArchivePeriod { get; set; }
        public short? D_ValiditePeriod { get; set; }
    }
}