// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class P_TIERS
    {
        public int cbMarq { get; set; }
        public short? T_Principal { get; set; }
        public string T_Val01T_Intitule { get; set; }
        public short? T_Val01T_TCompte { get; set; }
        public string T_Val01T_Compte { get; set; }
        public string T_Val02T_Intitule { get; set; }
        public short? T_Val02T_TCompte { get; set; }
        public string T_Val02T_Compte { get; set; }
        public string T_Val03T_Intitule { get; set; }
        public short? T_Val03T_TCompte { get; set; }
        public string T_Val03T_Compte { get; set; }
        public string T_Val04T_Intitule { get; set; }
        public short? T_Val04T_TCompte { get; set; }
        public string T_Val04T_Compte { get; set; }
        public string T_Val05T_Intitule { get; set; }
        public short? T_Val05T_TCompte { get; set; }
        public string T_Val05T_Compte { get; set; }
        public string T_Val06T_Intitule { get; set; }
        public short? T_Val06T_TCompte { get; set; }
        public string T_Val06T_Compte { get; set; }
        public string T_Val07T_Intitule { get; set; }
        public short? T_Val07T_TCompte { get; set; }
        public string T_Val07T_Compte { get; set; }
        public string T_Val08T_Intitule { get; set; }
        public short? T_Val08T_TCompte { get; set; }
        public string T_Val08T_Compte { get; set; }
        public string T_Val09T_Intitule { get; set; }
        public short? T_Val09T_TCompte { get; set; }
        public string T_Val09T_Compte { get; set; }
        public string T_Val10T_Intitule { get; set; }
        public short? T_Val10T_TCompte { get; set; }
        public string T_Val10T_Compte { get; set; }
        public short? T_Numerotation { get; set; }
        public short? T_Lg { get; set; }
        public string T_Racine { get; set; }
    }
}