// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtendueERP.Models.SageAPI
{
    public partial class V_DOCENTETE
    {
        public int cbMarq { get; set; }
        public short? DO_Domaine { get; set; }
        public short? DO_Type { get; set; }
        public string DO_Piece { get; set; }
        public DateTime? DO_Date { get; set; }
        public string DO_Ref { get; set; }
        public string DO_Tiers { get; set; }
        public int? CO_No { get; set; }
        public short? DO_Period { get; set; }
        public short? DO_Devise { get; set; }
        public decimal? DO_Cours { get; set; }
        public int? DE_No { get; set; }
        public int? LI_No { get; set; }
        public string CT_NumPayeur { get; set; }
        public short? DO_Expedit { get; set; }
        public short? DO_NbFacture { get; set; }
        public short? DO_BLFact { get; set; }
        public decimal? DO_TxEscompte { get; set; }
        public short? DO_Reliquat { get; set; }
        public short? DO_Imprim { get; set; }
        public string CA_Num { get; set; }
        public string DO_Coord01 { get; set; }
        public string DO_Coord02 { get; set; }
        public string DO_Coord03 { get; set; }
        public string DO_Coord04 { get; set; }
        public short? DO_Souche { get; set; }
        public DateTime? DO_DateLivr { get; set; }
        public short? DO_Condition { get; set; }
        public short? DO_Tarif { get; set; }
        public short? DO_Colisage { get; set; }
        public short? DO_TypeColis { get; set; }
        public short? DO_Transaction { get; set; }
        public short? DO_Langue { get; set; }
        public decimal? DO_Ecart { get; set; }
        public short? DO_Regime { get; set; }
        public short? N_CatCompta { get; set; }
        public short? DO_Ventile { get; set; }
        public int? AB_No { get; set; }
        public DateTime? DO_DebutAbo { get; set; }
        public DateTime? DO_FinAbo { get; set; }
        public DateTime? DO_DebutPeriod { get; set; }
        public DateTime? DO_FinPeriod { get; set; }
        public string CG_Num { get; set; }
        public short? DO_Statut { get; set; }
        public string DO_Heure { get; set; }
        public int? CA_No { get; set; }
        public int? CO_NoCaissier { get; set; }
        public short? DO_Transfere { get; set; }
        public short? DO_Cloture { get; set; }
        public string DO_NoWeb { get; set; }
        public short? DO_Attente { get; set; }
        public short? DO_Provenance { get; set; }
        public string CA_NumIFRS { get; set; }
        public int? MR_No { get; set; }
        public short? DO_TypeFrais { get; set; }
        public decimal? DO_ValFrais { get; set; }
        public short? DO_TypeLigneFrais { get; set; }
        public short? DO_TypeFranco { get; set; }
        public decimal? DO_ValFranco { get; set; }
        public short? DO_TypeLigneFranco { get; set; }
        public decimal? DO_Taxe1 { get; set; }
        public short? DO_TypeTaux1 { get; set; }
        public short? DO_TypeTaxe1 { get; set; }
        public decimal? DO_Taxe2 { get; set; }
        public short? DO_TypeTaux2 { get; set; }
        public short? DO_TypeTaxe2 { get; set; }
        public decimal? DO_Taxe3 { get; set; }
        public short? DO_TypeTaux3 { get; set; }
        public short? DO_TypeTaxe3 { get; set; }
        public short? DO_MajCpta { get; set; }
        public string DO_Motif { get; set; }
        public string CT_NumCentrale { get; set; }
        public string DO_Contact { get; set; }
        public short? DO_FactureElec { get; set; }
        public short? DO_TypeTransac { get; set; }
        public DateTime? DO_DateLivrRealisee { get; set; }
        public DateTime? DO_DateExpedition { get; set; }
        public string DO_FactureFrs { get; set; }
        public string DO_PieceOrig { get; set; }
        public Guid? DO_GUID { get; set; }
        public short? DO_EStatut { get; set; }
        public short? DO_DemandeRegul { get; set; }
        public int? ET_No { get; set; }
        public short? DO_Valide { get; set; }
        public short? DO_Coffre { get; set; }
        public string DO_CodeTaxe1 { get; set; }
        public string DO_CodeTaxe2 { get; set; }
        public string DO_CodeTaxe3 { get; set; }
        public decimal? DO_TotalHT { get; set; }
        public short? DO_StatutBAP { get; set; }
        public string CT_Intitule { get; set; }
        public string CA_Intitule { get; set; }
        public string CO_Nom { get; set; }
        public string DE_Intitule { get; set; }
        public string CG_Intitule { get; set; }
        public string TF_Intitule { get; set; }
        public decimal DL_MontantHT { get; set; }
        public decimal DL_MontantTTC { get; set; }
        public decimal? DL_MontantTVA { get; set; }
        public decimal RC_Montant { get; set; }
        public decimal? Reste { get; set; }
        public string EtatReglement { get; set; }
        public string DomaineIntitule { get; set; }
        public string TypeIntitule { get; set; }
    }
}